version: '3'

services:
  db:
    image: mysql:5.6.34
    volumes:
      - db_data:/var/lib/db/data
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  web:
    build:
      context: .
    working_dir: /mnt/rails
    volumes:
      - ./:/mnt/rails
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
volumes:
  db_data:

